import './globals.css'
import type { Metadata } from 'next'
import { Themes } from '@/components/Themes'
import { Inter } from 'next/font/google'
import { Toggle } from '@/components/Toggle'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode 
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Themes attribute='class' defaultTheme='dark'>
      <div className='w-screen justify-between p-8 flex'>
        <h1 className='font-extrabold capitalize text-4xl'>Magic The Gathering</h1>
        <Toggle/>
      </div>
      {children}
      </Themes>
      </body>
    </html>
  )
}
